# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit to internal track"
  lane :internal do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      track: 'internal',
      apk: '../build/app/outputs/apk/release/app-release.apk'
    )
  end

  desc "Promote to alpha track"
  lane :alpha do
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'alpha',
    )
  end

  desc "Promote to beta track / open testing"
  lane :beta do
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'beta',
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'production',
    )
  end
end
